[package]
name = "indexer"
version = "0.1.0"
authors = ["Ben Hansen <benhansenslc@gmail.com>"]

[dependencies]
regex = { version = "1.6", default_features = false, features = [ "std" ] }
rustc-serialize = "0.3"
